defmodule AshEvents.TestRepo.Migrations.AddTemporalCoverages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events_state_machine) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    alter table(:events_uuidv7) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    create table(:temporal_coverages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"))
      add(:plan, :text, null: false)
      add(:valid_at, :tstzrange, null: false)
    end

    execute("ALTER TABLE \"temporal_coverages\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")
  end

  def down do
    drop(table(:temporal_coverages))

    alter table(:events_uuidv7) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end

    alter table(:events_state_machine) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end
  end
end
